/**
 * mockData.js — Mock data used throughout the app
 * 
 * This provides realistic sample data for services, providers, bookings, etc.
 * Used when Firebase data is not yet loaded or for development/demo purposes.
 */

export const CATEGORIES = [
  { id: '1', name: 'Plumber', icon: 'water', color: '#3B82F6' },
  { id: '2', name: 'Electrician', icon: 'flash', color: '#F59E0B' },
  { id: '3', name: 'Cleaner', icon: 'sparkles', color: '#10B981' },
  { id: '4', name: 'Carpenter', icon: 'hammer', color: '#8B5CF6' },
  { id: '5', name: 'Painter', icon: 'color-palette', color: '#EF4444' },
  { id: '6', name: 'AC Repair', icon: 'snow', color: '#06B6D4' },
];

export const SERVICES = [
  {
    id: 's1',
    name: 'Full Home Cleaning',
    category: 'Cleaner',
    categoryId: '3',
    description: 'Complete deep cleaning of your entire home including kitchen, bathrooms, bedrooms, and living areas. Our professionals use eco-friendly products.',
    price: 1499,
    priceRange: '₹1,499 - ₹2,999',
    duration: '3-4 hours',
    rating: 4.8,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400',
    includes: [
      'Floor mopping & vacuuming',
      'Bathroom deep clean',
      'Kitchen cleaning & degreasing',
      'Dusting all surfaces',
      'Window cleaning (interior)',
      'Trash removal',
    ],
    providerId: 'p1',
  },
  {
    id: 's2',
    name: 'Electrical Wiring Repair',
    category: 'Electrician',
    categoryId: '2',
    description: 'Expert electrical repair and wiring services. Our certified electricians handle all types of electrical issues safely.',
    price: 499,
    priceRange: '₹499 - ₹1,499',
    duration: '1-2 hours',
    rating: 4.7,
    reviewCount: 218,
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400',
    includes: [
      'Inspection & diagnosis',
      'Wire replacement',
      'Switch/socket repair',
      'MCB/fuse repair',
      'Safety testing',
    ],
    providerId: 'p2',
  },
  {
    id: 's3',
    name: 'Pipe Leak Repair',
    category: 'Plumber',
    categoryId: '1',
    description: 'Quick and reliable pipe leak fixing services. We fix all types of leaks — kitchen, bathroom, and outdoor plumbing.',
    price: 399,
    priceRange: '₹399 - ₹999',
    duration: '1-2 hours',
    rating: 4.6,
    reviewCount: 187,
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400',
    includes: [
      'Leak inspection',
      'Pipe sealing/replacement',
      'Joint tightening',
      'Pressure testing',
      'Cleanup after repair',
    ],
    providerId: 'p3',
  },
  {
    id: 's4',
    name: 'AC Service & Repair',
    category: 'AC Repair',
    categoryId: '6',
    description: 'Complete AC servicing including gas refill, cleaning, and repair. Keep your AC running efficiently all year.',
    price: 699,
    priceRange: '₹699 - ₹2,499',
    duration: '1-3 hours',
    rating: 4.9,
    reviewCount: 456,
    image: 'https://images.unsplash.com/photo-1631545806609-35d4ae440431?w=400',
    includes: [
      'Filter cleaning',
      'Coil cleaning',
      'Gas pressure check',
      'Thermostat check',
      'Gas refill (if needed)',
      'General inspection',
    ],
    providerId: 'p4',
  },
  {
    id: 's5',
    name: 'Furniture Assembly',
    category: 'Carpenter',
    categoryId: '4',
    description: 'Professional furniture assembly and repair services. We assemble IKEA, custom, and all types of furniture.',
    price: 599,
    priceRange: '₹599 - ₹1,999',
    duration: '2-4 hours',
    rating: 4.5,
    reviewCount: 129,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400',
    includes: [
      'Furniture unpacking',
      'Full assembly',
      'Hardware installation',
      'Wall mounting (if applicable)',
      'Cleanup',
    ],
    providerId: 'p5',
  },
  {
    id: 's6',
    name: 'Wall Painting',
    category: 'Painter',
    categoryId: '5',
    description: 'Professional wall painting with premium paints. Transform your room with a fresh coat of paint.',
    price: 2499,
    priceRange: '₹2,499 - ₹7,999',
    duration: '1-2 days',
    rating: 4.7,
    reviewCount: 203,
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400',
    includes: [
      'Surface preparation',
      'Primer application',
      '2 coats of premium paint',
      'Edge detailing',
      'Furniture covering & protection',
      'Post-painting cleanup',
    ],
    providerId: 'p6',
  },
  {
    id: 's7',
    name: 'Bathroom Cleaning',
    category: 'Cleaner',
    categoryId: '3',
    description: 'Thorough bathroom deep cleaning service. We scrub every corner and leave your bathroom sparkling clean.',
    price: 599,
    priceRange: '₹599 - ₹999',
    duration: '1-2 hours',
    rating: 4.6,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400',
    includes: [
      'Toilet deep clean',
      'Tile scrubbing',
      'Mirror cleaning',
      'Faucet polishing',
      'Floor mopping',
      'Drain cleaning',
    ],
    providerId: 'p1',
  },
  {
    id: 's8',
    name: 'Fan Installation',
    category: 'Electrician',
    categoryId: '2',
    description: 'Ceiling fan and exhaust fan installation services. Safe and secure mounting by certified professionals.',
    price: 349,
    priceRange: '₹349 - ₹699',
    duration: '30-60 mins',
    rating: 4.8,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=400',
    includes: [
      'Old fan removal (if needed)',
      'Mounting bracket installation',
      'Fan assembly & installation',
      'Wiring connection',
      'Speed regulator setup',
      'Testing',
    ],
    providerId: 'p2',
  },
];

export const PROVIDERS = [
  {
    id: 'p1',
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    email: 'rajesh.k@email.com',
    profileImage: 'https://randomuser.me/api/portraits/men/1.jpg',
    rating: 4.8,
    reviewCount: 342,
    services: ['Cleaner'],
    experience: '5 years',
    completedJobs: 580,
    isOnline: true,
    location: { latitude: 19.076, longitude: 72.8777 },
  },
  {
    id: 'p2',
    name: 'Suresh Sharma',
    phone: '+91 98765 43211',
    email: 'suresh.s@email.com',
    profileImage: 'https://randomuser.me/api/portraits/men/2.jpg',
    rating: 4.7,
    reviewCount: 218,
    services: ['Electrician'],
    experience: '8 years',
    completedJobs: 920,
    isOnline: true,
    location: { latitude: 19.082, longitude: 72.881 },
  },
  {
    id: 'p3',
    name: 'Amit Patel',
    phone: '+91 98765 43212',
    email: 'amit.p@email.com',
    profileImage: 'https://randomuser.me/api/portraits/men/3.jpg',
    rating: 4.6,
    reviewCount: 187,
    services: ['Plumber'],
    experience: '6 years',
    completedJobs: 450,
    isOnline: false,
    location: { latitude: 19.071, longitude: 72.873 },
  },
  {
    id: 'p4',
    name: 'Vikram Singh',
    phone: '+91 98765 43213',
    email: 'vikram.s@email.com',
    profileImage: 'https://randomuser.me/api/portraits/men/4.jpg',
    rating: 4.9,
    reviewCount: 456,
    services: ['AC Repair'],
    experience: '10 years',
    completedJobs: 1200,
    isOnline: true,
    location: { latitude: 19.079, longitude: 72.879 },
  },
  {
    id: 'p5',
    name: 'Deepak Verma',
    phone: '+91 98765 43214',
    email: 'deepak.v@email.com',
    profileImage: 'https://randomuser.me/api/portraits/men/5.jpg',
    rating: 4.5,
    reviewCount: 129,
    services: ['Carpenter'],
    experience: '7 years',
    completedJobs: 380,
    isOnline: true,
    location: { latitude: 19.085, longitude: 72.885 },
  },
  {
    id: 'p6',
    name: 'Manoj Tiwari',
    phone: '+91 98765 43215',
    email: 'manoj.t@email.com',
    profileImage: 'https://randomuser.me/api/portraits/men/6.jpg',
    rating: 4.7,
    reviewCount: 203,
    services: ['Painter'],
    experience: '12 years',
    completedJobs: 750,
    isOnline: false,
    location: { latitude: 19.068, longitude: 72.870 },
  },
];

export const REVIEWS = [
  {
    id: 'r1',
    serviceId: 's1',
    userId: 'u1',
    userName: 'Priya Mehta',
    userImage: 'https://randomuser.me/api/portraits/women/1.jpg',
    rating: 5,
    comment: 'Amazing cleaning service! My home looks brand new. The team was very thorough and professional.',
    date: '2025-12-15',
  },
  {
    id: 'r2',
    serviceId: 's1',
    userId: 'u2',
    userName: 'Ankit Joshi',
    userImage: 'https://randomuser.me/api/portraits/men/7.jpg',
    rating: 4,
    comment: 'Good service overall. Could have spent more time on the kitchen area.',
    date: '2025-12-10',
  },
  {
    id: 'r3',
    serviceId: 's2',
    userId: 'u3',
    userName: 'Neha Gupta',
    userImage: 'https://randomuser.me/api/portraits/women/2.jpg',
    rating: 5,
    comment: 'Fixed the wiring issue in 30 minutes! Very skilled electrician.',
    date: '2025-12-08',
  },
  {
    id: 'r4',
    serviceId: 's4',
    userId: 'u4',
    userName: 'Rahul Nair',
    userImage: 'https://randomuser.me/api/portraits/men/8.jpg',
    rating: 5,
    comment: 'Best AC service ever! The technician was knowledgeable and cleaned everything perfectly.',
    date: '2025-12-20',
  },
  {
    id: 'r5',
    serviceId: 's3',
    userId: 'u5',
    userName: 'Sneha Reddy',
    userImage: 'https://randomuser.me/api/portraits/women/3.jpg',
    rating: 4,
    comment: 'Fixed the leak quickly. Professional and punctual.',
    date: '2025-12-05',
  },
];

export const TIME_SLOTS = [
  { id: 't1', label: 'Morning', time: '09:00 AM - 12:00 PM', icon: 'sunny' },
  { id: 't2', label: 'Afternoon', time: '12:00 PM - 03:00 PM', icon: 'partly-sunny' },
  { id: 't3', label: 'Evening', time: '03:00 PM - 06:00 PM', icon: 'cloudy-night' },
  { id: 't4', label: 'Night', time: '06:00 PM - 09:00 PM', icon: 'moon' },
];

export const BOOKING_STATUSES = {
  CONFIRMED: 'confirmed',
  PROVIDER_ASSIGNED: 'provider_assigned',
  ON_THE_WAY: 'on_the_way',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
};

export const ONBOARDING_SLIDES = [
  {
    id: '1',
    title: 'Book Home Services',
    description: 'From plumbing to painting, find trusted professionals for every home service need — all in one app.',
    icon: 'home',
    color: '#4F46E5',
  },
  {
    id: '2',
    title: 'Verified Professionals',
    description: 'All our service providers are background-verified, skilled, and rated by real customers.',
    icon: 'shield-checkmark',
    color: '#10B981',
  },
  {
    id: '3',
    title: 'Track in Real-Time',
    description: 'Track your booking status live, from confirmation to completion. Know exactly when your pro arrives.',
    icon: 'location',
    color: '#F59E0B',
  },
];
